baseURL = "https://www.borispersiantest.netlify.com"
disqusShortname = ""
languageCode = "fr-FR"
languageName = "fr"
paginate = "5"
theme = "persian"
title = "Boris Rybaltchenko - Architecte énergéticien hmonp - BRAV = Bâtir Rénover Avec le Vivant - brav.fr"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
URL = "contact"
name = "Nous contacter"
url = "contact"
weight = 5
[[menu.main]]
URL = "/"
name = "Nos valeurs"
weight = 1
[[menu.main]]
URL = "/"
name = "Projets"
weight = 2
[[menu.main]]
URL = "/"
name = "Démarche Bioclimatique"
weight = 3
[[menu.main]]
URL = "/"
name = "Brav"
weight = 4
[outputs]
home = ["HTML", "RSS", "json"]
[params]
author = "Boris Rybaltchenko Architecte- Architecte énergéticien - brav.fr"
contact_form_action = "#"
copyright = "<br><br><br><br><b>B</b>âtir  -  <b>R</b>énover  -  <b>A</b>vec  -  le <b>V</b>ivant<br>"
description = "brav.fr,Boris Rybaltchenko Architecte- Architecte énergéticien, bâtir, rénover, réhabiliter, avec, le vivant, écorénovation, paille, pro-paille, construire en chanvre, cenc, ceph, concepteur bâtiment passif, maison passive"
logo = "images/logo.png"
search = false
[params.cookies]
enable = false
expire_days = 2
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
icon = "ti-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
title = "twitter"
[[params.social]]
icon = "ti-instagram"
link = "#"
title = "instagram"
[[params.social]]
icon = "ti-github"
link = "#"
title = "github"
[[params.social]]
icon = "ti-linkedin"
link = "#"
title = "linkedin"
